# Generated by Django 2.2 on 2021-03-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('optype', models.CharField(choices=[('encode', '添加水印'), ('decode', '解析水印')], default='encode', max_length=10)),
                ('upload_file', models.FileField(upload_to='./data/upload/digital_works')),
                ('upload_filename', models.CharField(blank=True, max_length=100)),
                ('upload_fstatus', models.CharField(blank=True, choices=[('raw', '无水印'), ('encoded', '有水印')], max_length=10)),
                ('upload_ftype', models.CharField(blank=True, choices=[('image', '图片'), ('audio', '音频'), ('video', '视频')], max_length=10)),
                ('upload_fformat', models.CharField(blank=True, choices=[('png', 'png'), ('jpg', 'jpg'), ('jepg', 'jepg'), ('wav', 'wav'), ('mp4', 'mp4')], max_length=10)),
                ('embed_mode', models.CharField(blank=True, choices=[('img', '图片水印'), ('str', '字符串水印')], max_length=50)),
                ('upload_watermark_img', models.ImageField(blank=True, upload_to='./data/upload/watermarks')),
                ('upload_watermark_img_name', models.CharField(blank=True, max_length=20)),
                ('upload_watermark_string', models.CharField(default='default watermark', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('optype', models.CharField(choices=[('encode', '添加水印'), ('decode', '解析水印')], default='encode', max_length=10)),
                ('download_file', models.FileField(upload_to='./data/download')),
                ('download_filename', models.CharField(default='f', max_length=100)),
                ('download_ftype', models.CharField(choices=[('raw', '无水印'), ('encoded', '有水印')], default='encoded', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
    ]
