# Generated by Django 2.2 on 2021-03-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='upload_file',
            field=models.FileField(upload_to='E:\\Project\\learnDjango\\ODWCPP\\data/upload/digital_works'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='upload_watermark_img',
            field=models.ImageField(blank=True, upload_to='E:\\Project\\learnDjango\\ODWCPP\\data/upload/watermarks'),
        ),
    ]
