# Generated by Django 2.2 on 2021-03-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210329_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='embed_mode',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='upload_watermark_img',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='upload_watermark_img_name',
        ),
    ]
