# Generated by Django 2.2 on 2021-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210329_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraction',
            old_name='upload_filename',
            new_name='upload_filepath',
        ),
        migrations.AlterField(
            model_name='useraction',
            name='upload_file',
            field=models.FileField(upload_to='E:\\Project\\learnDjango\\ODWCPP\\data/upload'),
        ),
    ]
