# Generated by Django 2.2 on 2021-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210329_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='upload_file',
            field=models.FileField(upload_to='E:\\Project\\learnDjango\\ODWCPP\\data\\upload'),
        ),
    ]
